name: Maven Package

on:
  push:
    branches:
      - main #branch for this repo
      - 'testSub1/main' #repo and branch for submodule
      - 'testSub2/main' #repo and branch for submodule

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Main Workflow
      uses: actions/github-script@v5
      with:
        script: |
          try {
            const { data: workflows } = await github.actions.listRepoWorkflows({
              owner: 'botian123123',
              repo: 'testMain'
            });
            
            const mainWorkflow = workflows.workflows.find(workflow => workflow.name === 'build.yml');
            
            if (mainWorkflow) {
              await github.actions.reRunWorkflow({
                owner: 'botian123123',
                repo: 'testMain',
                workflow_id: mainWorkflow.id
              });
            } else {
              console.log('Main workflow not found.');
            }
          } catch (error) {
            console.error('Error:', error);
          }

  build:
    runs-on: ubuntu-latest

    needs: trigger

    steps:
      - name: setup java env.
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build sub2
        uses: actions/checkout@v4
        with:
          repository: botian123123/testSub2.git
          ref: main
          path: path_to_sub2
      - run: |
          cd path_to_sub2/sub2
          mvn install -DskipTests
      - name: Build sub1
        uses: actions/checkout@v4
        with:
          repository: botian123123/testSub1.git
          ref: main
          path: path_to_sub1
      - run: |
          cd path_to_sub1/cicdtest
          mvn install -DskipTests
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: path_to_main
      - name: build main .jar
        run: |
          cd path_to_main/demo
          mvn install
          mkdir ${{ github.workspace }}/handler
          cd target
          mv handler* ${{ github.workspace }}/handler/
          cd ${{ github.workspace }}/handler/
          ls



